# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: ['*']
  pull_request:
    branches:  ['*']

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
